to_do_list/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todolist.urls')),
]

#根路由

todolist/urls.py
from django.urls import path,include
from . import views

app_name = 'todolist'

#起一个app的名字，指定前缀
#起一个name,用于访问
#避免网址名，网页名冲突


urlpatterns = [
    path('home/', views.home,name='主页'),
    path('about/', views.about,name='关于'),
    path('edit/<forloop_counter>', views.edit,name='编辑'),
    path('del/<forloop_counter>', views.delete,name='删除'),
    path('cross/<forloop_counter>', views.cross,name='划掉'),
]

#子路由
#传一个变量

todolist/models.py
from django.db import models


class Todo(models.Model):
    thing = models.CharField(max_length=50)
    done = models.BooleanField(default=False)


    def __str__(self):
        pass

todolist/views.py
from django.shortcuts import render,redirect

lst = [
    {'待办事项':'学习','已完成':False},
    {'待办事项':'啦啦啦','已完成':True}
]


def home(request):
    global lst
    if request.method == "POST":
        if request.POST['待办事项'] == '':
            content = {'清单': lst,'警告':'请输入内容！'}
            return render(request, "todolist/home.html", content)
        else:
            lst.append({'待办事项':request.POST['待办事项'],'已完成':False})
            content = { '清单': lst,'信息':'添加成功'}
            return render(request,"todolist/home.html",content)
    else:
        content = {'清单': lst}
        return render(request, "todolist/home.html", content)


def about(request):
    return render(request, "todolist/about.html")


def edit(request,forloop_counter):
    global lst

    if request.method == "POST":
        if request.POST['已修改事项'] == '':
            return render(request, "todolist/edit.html", {'警告': '请输入内容'})
        else:
            lst[int(forloop_counter) - 1]['待办事项'] = request.POST['已修改事项']
            return redirect("todolist:主页")
    elif request.method == "GET":
        content = { '待修改事项':lst[int(forloop_counter) -1]['待办事项']}
        return render(request, "todolist/edit.html",content)


def delete(request,forloop_counter):
    global lst
    lst.pop(int(forloop_counter)-1)

    return redirect("todolist:主页")


def cross(request,forloop_counter):
    global lst
    if request.POST['完成状态'] == '已完成':
        lst[int(forloop_counter) - 1]['已完成'] = True
        return redirect("todolist:主页")
    else:
        lst[int(forloop_counter) - 1]['已完成'] = False
        return redirect("todolist:主页")

todolist/templates/todolist/about.html
{% extends "todolist/base.html" %}
{% load static %}
<title>{% block 标题 %}关于{% endblock 标题 %}</title>
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 主体 %}
    <br>
    <h4>待办清单工具，规划日常事务</h4>
{% endblock 主体 %}

todolist/templates/todolist/base.html
<!--&lt;!&ndash;网页的继承，根网页 extends&ndash;&gt;-->
<!--&lt;!&ndash;block块继承和改变一些元素&#45;&#45; block>-->
<!--&lt;!&ndash;css的继承&#45;&#45; block>-->
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block 标题 %}未命名{% endblock 标题 %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Custom styles for this template -->
      <link rel="stylesheet" href="{% static 'todolist/css/base.css' %}">
      <link rel="stylesheet" href="{% block css %}{% endblock css %}">
    <!--<link href="navbar-top.css" rel="stylesheet">-->
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% block 主页高亮 %}{% endblock 主页高亮 %}">
        <a class="nav-link" href="{% url 'todolist:主页' %}">待办清单</a>
      </li>
      <li class="nav-item {% block 关于高亮 %}{% endblock 关于高亮 %}">
        <a class="nav-link" href="{% url 'todolist:关于' %}">关于本站</a>
      </li>

    </ul>
    <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end" method="POST" action="">
      {% csrf_token %}
        <input name="待办事项" class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
    </form>
  </div>
</nav>

    <main role="main" class="container">
        {% block 主体 %}

        {% endblock 主体 %}
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>




    </script>
  </body>
</html>

todolist/templates/todolist/edit.html
{% extends "todolist/base.html" %}
{% load static %}
{% block css %}{% static 'todolist/css/edit.css' %}{% endblock css %}
<title>{% block 标题 %}编辑{% endblock 标题 %}</title>
{% block 主体 %}
    <br>
    <form id="form-edit" method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
    <label for="editTodo"></label>
    <input name="已修改事项" class="form-control form-control-lg" id="editTodo" type="text" value="{{ 待修改事项 }}">
    <small id="help" class="form-text text-muted">上方输入待办事项</small>
  </div>
        {% if 警告 %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong><center>{{ 警告 }}</center></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
          </button>
          </div>
      {% endif %}
  <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
<!--</main>-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">

    </script>
  <!--</body>-->
<!--</html>-->
{% endblock 主体 %}

todolist/templates/todolist/home.html
{% extends "todolist/base.html" %}

{% load static %}
{% block css %}{% static 'todolist/css/home.css' %}{% endblock css %}
<title>{% block 标题 %}你的个人待办清单{% endblock 标题 %}</title>
{% block 主页高亮 %}active{% endblock 主页高亮 %}
{% block 主体 %}

{% if 警告 %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong><center>{{ 警告 }}</center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
  </button>
    </div>
{% endif %}
{% if 信息 %}
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <strong><center>{{ 信息 }}</center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
  </button>
    </div>
{% endif %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-light">
              <tr>
                  <th >序号</th>
                  <th >待办事项</th>
                  <th>编辑</th>
                  <th >划掉</th>
                  <th >删除</th>
              </tr>
            </thead>
            <tbody class="no-underline">
            {% for everything in 清单 %}
            {% if everything.已完成 %}
                 <tr class="table-dark">
                  <th class="text-dark" scope="row">{{ forloop.counter }}</th>

                  <td class="text-dark" id="line-through">{{everything.待办事项}}</td>
                     <td><a class="text-secondary" >不可编辑</a></td>
                  <td>
                      <form method="POST" action="{% url 'todolist:划掉' forloop.counter %}">
                          {% csrf_token %}
                          <input type="hidden" value="未完成" name="完成状态">
                          <button type="submit" class="btn btn-danger btn-sm">撤销</button>
                      </form>
                  </td>
                  <td>

                          <form method="POST" action="{% url 'todolist:删除' forloop.counter %}">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger btn-sm" >删除</button>
                      </form>

                  </td>
              </tr>
            {% else %}
                 <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{everything.待办事项}}</td>
                  <td><a class="text-info" href="{% url 'todolist:编辑' forloop.counter%}">编辑</a></td>
                  <td>
                      <form method="POST" action="{% url 'todolist:划掉' forloop.counter %}">
                          {% csrf_token %}
                          <input type="hidden" value="已完成" name="完成状态">
                          <button type="submit" class="btn btn-danger btn-sm">划掉</button>
                      </form>
                  </td>
                  <td>
                      <form method="POST" action="{% url 'todolist:删除' forloop.counter %}">
                          {% csrf_token %}
                          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModal">删除</button>
                      </form>



                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">请确认</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            确定要删除<strong> 未办事项：{{everything.待办事项}}</strong>吗？
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                              <form method="POST" action="{% url 'todolist:删除' forloop.counter %}">
                                {% csrf_token %}
                            <button type="submit" class="btn btn-primary">确认</button>
                              </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                 </tr>
            {% endif %}

            {% endfor %}

              <!--<tr>-->
                  <!--<th scope="row">2</th>-->
                  <!--<td>看一会小说</td>-->
                  <!--<td><a class="text-info" href="#">编辑</a></td>-->
                  <!--<td><a class="text-info" href="#">划掉</a></td>-->
                  <!--<td><a class="text-info" href="#">删除</a></td>-->
              <!--</tr>-->
              <!--<tr>-->
                  <!--<th scope="row">3</th>-->
                  <!--<td>小睡一下</td>-->
                  <!--<td><a class="text-info" href="#">编辑</a></td>-->
                  <!--<td><a class="text-info" href="#">划掉</a></td>-->
                  <!--<td><a class="text-info" href="#">删除</a></td>-->
              <!--</tr>-->


            </tbody>
        </table>

    </div>
{% endblock 主体 %}